name: build

on:
  push:
    branches: [master]
    paths:
      - "Dockerfile"
      - ".github/**"
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        poetry_version: ["1.4.0", "1.4.1", "1.4.2", "1.5.0", "1.5.1"]
    runs-on: ubuntu-latest
    env:
      PYTHON_VERSION: 3.11.4
      POETRY_VERSION: ${{ matrix.poetry_version }}
    steps:
      - uses: docker/setup-qemu-action@v2
      - uses: docker/setup-buildx-action@v2
      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-
      - name: Login to DockerHub
        id: dockerhub_login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          tags: |
            docker.io/blackdark93/python-poetry:${{ env.POETRY_VERSION }}
            docker.io/blackdark93/python-poetry:latest
          platforms: linux/amd64,linux/ppc64le,linux/arm64
          build-args: POETRY_VERSION=${{ env.POETRY_VERSION }}
          push: true
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache

  dockerhub-description:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Update DockerHub description
        uses: peter-evans/dockerhub-description@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
          short-description: Python Poetry
          readme-filepath: ./README.md
          repository: blackdark93/python-poetry
